### ISSUE TITLE
Wounded soldiers dont restore stats

### ISSUE THREAD

**Issue by nightmaRok** [long-war-2/lwotc#319]
I play with red fog, so its might be it. As i know minimum stats of aim is 55. When i play alpha 4 all was fine

![Wounded_01](https://user-images.githubusercontent.com/51829747/60945455-42538300-a2f4-11e9-94ef-d7c8597ebe0e.jpg)

Use console command healallsoldiers, nothing change

![Wounded_02](https://user-images.githubusercontent.com/51829747/60945569-93fc0d80-a2f4-11e9-804b-4a4952c02bdd.jpg)

[save_Wounded_bug.zip](https://github.com/long-war-2/lwotc/files/3375974/save_Wounded_bug.zip)

**Comment by jmartinez989** [comment]
yeah this is an issue with red fog. In my particular case soldiers even lose stats like aim even if they never got wounded at all. Not sure what happened in the latest updates but red fog is kind of messed up currently. Would recommend to play without red fog until the issue is fixed or you can use console commands to give your soldiers their stats back.

**Comment by nightmaRok** [comment]
Its already was fixed by pledbrook in alpha 5.1 hotfix.
https://www.reddit.com/r/xcom2mods/comments/ca4z1p/long_war_2_wotc_alpha_5_ready_for_testing/

**Comment by pledbrook** [comment]
@nightmaRok So it's working fine now? Or is there still an issue with soldier stats in 5.1?

**Comment by nightmaRok** [comment]
Last time i played LWotc i download 2 files from reddit (LW_Overhaul.u and LW_Toolbox_Integrated.u), looks like its work fine for me

**Comment by pledbrook** [comment]
Great. I'll be releasing the patches plus a fix for the melee attack hanging bug in an alpha 6.
